ALTER TABLE `tbattendanceapprove`
  MODIFY COLUMN `beginTime` DATETIME DEFAULT NULL COMMENT '开始时间',
  MODIFY COLUMN `endTime` DATETIME DEFAULT NULL COMMENT '结束时间',
  MODIFY COLUMN `createTime` DATETIME DEFAULT NULL,
  MODIFY COLUMN `workDate` DATETIME DEFAULT NULL COMMENT '申请日期';
