-- SaaS 改造 P3：API→菜单权限映射表（主库 hrsystem，全局配置）
CREATE TABLE IF NOT EXISTS tb_api_permission (
    id INT AUTO_INCREMENT PRIMARY KEY,
    api_prefix VARCHAR(200) NOT NULL COMMENT 'API 前缀或完整路径',
    menu_paths VARCHAR(500) NOT NULL COMMENT '允许访问的菜单路径，逗号分隔',
    match_type VARCHAR(10) NOT NULL DEFAULT 'prefix' COMMENT 'prefix=前缀匹配 exact=精确匹配',
    sortno INT NOT NULL DEFAULT 0 COMMENT '排序，越小越优先',
    remark VARCHAR(200) NULL,
    UNIQUE KEY uk_api_prefix (api_prefix)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API 与菜单路径权限映射';

-- 初始种子数据（与原 ApiPermissionPathSupport 硬编码一致）
INSERT INTO tb_api_permission (api_prefix, menu_paths, match_type, sortno, remark) VALUES
('/tbLoginUser','/hrm/system/loginUser','prefix',100,NULL),
('/tbRoleMenu','/hrm/system/rolePermission','prefix',101,NULL),
('/tbRoleTypes','/hrm/system/rolePermission','prefix',102,NULL),
('/tbMenu','/hrm/system/menu','prefix',103,NULL),
('/menu','/hrm/system/menu','prefix',104,NULL),
('/hrmDept','/hrm/dept','prefix',200,NULL),
('/hrmEmployeeContract','/hrm/employee','prefix',201,NULL),
('/hrmEmployeeFile','/hrm/employee','prefix',202,NULL),
('/hrmEmployeePost','/hrm/employee','prefix',203,NULL),
('/hrmEmployee/SocialSecurity','/hrm/employee','prefix',204,NULL),
('/hrmEmployee','/hrm/employee','prefix',205,NULL),
('/hrmRecruitChannel','/hrm/employee','prefix',206,NULL),
('/workPlan','/hrm/attendance/records','prefix',300,NULL),
('/workPlanProduct','/hrm/attendance/workplanProduct','prefix',301,NULL),
('/attendanceData','/hrm/attendance/scheduling','prefix',302,NULL),
('/hrmAttendanceClock','/hrm/attendance/index','prefix',303,NULL),
('/hrmAttendanceEmpMonthRecord','/hrm/attendance/index','prefix',304,NULL),
('/hrmAttendanceApproval','/hrm/attendance/approval','prefix',305,NULL),
('/hrmOvertimeNightStatistics','/hrm/attendance/overtimeNight','prefix',306,NULL),
('/hrmWorkweekSetting','/hrm/attendance/workweek','prefix',307,NULL),
('/hrmAttendanceGroupRelationDept','/hrm/attendance/scheduling','prefix',308,NULL),
('/hrmAttendanceGroupRelationEmployee','/hrm/attendance/scheduling','prefix',309,NULL),
('/hrmAttendanceGroup','/hrm/attendance/scheduling','prefix',310,NULL),
('/hrmAttendancePoint','/hrm/attendance/scheduling','prefix',311,NULL),
('/hrmAttendanceRule/queryAttendanceRulePageList','/hrm/attendance/scheduling,/manage/attendance','exact',312,NULL),
('/hrmAttendanceRule/addAttendanceRule','/manage/attendance','exact',313,NULL),
('/hrmAttendanceRule/delete','/manage/attendance','exact',314,NULL),
('/hrmAttendanceRule','/hrm/attendance/scheduling','prefix',315,NULL),
('/hrmAttendanceShift','/hrm/attendance/scheduling','prefix',316,NULL),
('/hrmAttendanceInfo','/hrm/attendance/scheduling','prefix',317,NULL),
('/hrmProduceAttendance','/hrm/attendance/index','prefix',318,NULL),
('/hrmEmployeeLeaveRecord','/hrm/attendance/index','prefix',319,NULL),
('/hrmEmployeeOverTimeRecord','/hrm/attendance/overtimeNight','prefix',320,NULL),
('/hrmSalaryArchives','/hrm/salary/archives','prefix',400,NULL),
('/hrmSalaryMonthRecord','/hrm/salary/index','prefix',401,NULL),
('/hrmSalaryHistoryRecord','/hrm/salary/history','prefix',402,NULL),
('/hrmSalarySlipRecord','/hrm/salary/record','prefix',403,NULL),
('/hrmSalarySlipTemplateOption','/hrm/salary/record','prefix',404,NULL),
('/hrmSalarySlipTemplate','/hrm/salary/record','prefix',405,NULL),
('/hrmSalaryBasic/findAll','/hrm/salary/index,/manage/salary','exact',406,NULL),
('/hrmSalaryBasic/saveSalaryBasic','/hrm/salary/index,/manage/salary','exact',407,NULL),
('/hrmSalaryBasic/queryById','/hrm/salary/index,/manage/salary','exact',408,NULL),
('/hrmSalaryBasic/deleteSalaryBasic','/hrm/salary/index,/manage/salary','exact',409,NULL),
('/hrmSalaryConfig','/manage/salary,/manage/salaryConfig','prefix',410,NULL),
('/hrmSalaryBasic','/manage/salary','prefix',411,'注意：排在 /hrmSalaryBasic/* 精确项之后'),
('/hrmSalaryChangeTemplate','/manage/salary','prefix',412,NULL),
('/hrmBonus/importBonus','/hrm/bonus/payroll','exact',420,NULL),
('/hrmBonus/importTaxOnlyBonus','/hrm/bonus/taxOnly','exact',421,NULL),
('/hrmBonus/queryBounsList','/hrm/bonus/payroll,/hrm/bonus/taxOnly','exact',422,NULL),
('/hrmBonus','/hrm/bonus/payroll','prefix',423,NULL),
('/hrmAdditional','/hrm/salary/addition','prefix',430,NULL),
('/hrmEmployeeAdditional','/hrm/salary/addition','prefix',431,NULL),
('/hrmPersonalIncomeTax','/hrm/salary/tax','prefix',432,NULL),
('/hrmHolidayDeduction/queryHolidayDeductionList','/hrm/salary/addition,/manage/vacation','exact',433,NULL),
('/hrmHolidayDeduction/saveHolidayDeduction','/manage/vacation','exact',434,NULL),
('/hrmHolidayDeduction','/hrm/salary/addition','prefix',435,NULL),
('/hrmRemainingVaction','/manage/vacation','prefix',436,NULL),
('/hrmInsuranceMonthEmpRecord','/hrm/insurance-scheme/index','prefix',500,NULL),
('/hrmInsuranceMonthRecord','/hrm/insurance-scheme/index','prefix',501,NULL),
('/hrmInsuranceProject','/manage/insurance-scheme','prefix',502,NULL),
('/hrmInsuranceScheme/index','/hrm/insurance-scheme/index,/manage/insurance-scheme','exact',503,NULL),
('/hrmInsuranceScheme/queryInsuranceSchemeById','/hrm/insurance-scheme/index,/manage/insurance-scheme','exact',504,NULL),
('/hrmInsuranceScheme/deleteInsuranceScheme','/manage/insurance-scheme','exact',505,NULL),
('/hrmInsuranceScheme','/hrm/insurance-scheme/index','prefix',506,NULL),
('/dict','/hrm/dataConfig/index','prefix',600,NULL),
('/tbCompanyList','/hrm/dataConfig/index','prefix',601,NULL),
('/report','/hrm/dataConfig/index','prefix',602,NULL),
('/tempworker','/hrm/dataConfig/index','prefix',603,NULL),
('/workPlanApplication','/hrm/attendance/scheduling','prefix',700,NULL),
('/tenant/provision','/hrm/system/tenant','prefix',800,'SaaS 租户开通'),
('/tenant/list','/hrm/system/tenant','prefix',801,'租户列表'),
('/tenant/tables','/hrm/system/tenant','prefix',802,'租户表清单'),
('/tenant/reloadApiPermission','/hrm/system/tenant','prefix',803,'刷新权限映射'),
('/tenant/resetAdminPassword','/hrm/system/tenant','prefix',804,'重置租户管理员密码'),
('/backup','/hrm/system/databaseBackup','prefix',900,'数据库备份'),
('/dashboard/permission/all','/hrm/system/dashboardPermission','exact',910,'看板权限查询'),
('/dashboard/permission/save','/hrm/system/dashboardPermission','exact',911,'看板权限保存'),
('/dashboard/permission/hiddenKpis','/hrm/system/dashboardPermission','exact',912,'看板隐藏元素查询'),
('/companyPermission','/hrm/system/companyPermission','prefix',920,'企业权限管理'),
('/mpPermission','/hrm/system/miniappPermission','prefix',933,'排班小程序权限配置页')
ON DUPLICATE KEY UPDATE menu_paths=VALUES(menu_paths), match_type=VALUES(match_type);
